### ISSUE TITLE
test_main.py error 

### ISSUE THREAD

**Issue by archanabhardwaj** [goeastagent/MildInt#1]
Hello 
I am running test code entitled as  test_main.py and got following error 

line 13, in generate_overlapRIDs
    result = sets.next()
AttributeError: 'map' object has no attribute 'next'

could you help to fix this issue ?

**Comment by goeastagent** [comment]
If you work under python 3.x, following code will work,

result = set(RIDs_list[0])                               
for i in range(1,len(RIDs_list)):                        
     result = result & set(RIDs_list[i])

instead of 
sets = iter(map(set, RIDs_list))                         
result = sets.next()                                     
for s in sets:                                           
     result = result.intersection(s) 

in DataManager.py file

**Comment by archanabhardwaj** [comment]
Hi 

I am working on python 3.7 I changed code in DataManager.py. but still no success. I am having same issue.

**Comment by goeastagent** [comment]
what is the error code? if you changed the code then sets.next() is not the error anymore

**Comment by archanabhardwaj** [comment]
Here is error code : 
Traceback (most recent call last):
  File "test_main.py", line 16, in <module>
    overlap_RIDs = dm.generate_overlapRIDs([RIDs_cog,RIDs_csf,RIDs_MRI,RIDs_demo])
  File "Python37/DataManager.py", line 13, in generate_overlapRIDs
    result = sets.next()
AttributeError: 'map' object has no attribute 'next'

Issue is with DataManager.py , but I changed code as suggested by you. 

Thanks in advance
